# Implementações Para a Disciplina de Métodos Quantitativos

### Aluno: João Pedro Oliveira Batisteli

**Bibliotecas Utilizadas:**

- **Numpy**: A biblioteca NumPy é uma biblioteca Python para computação científica. Ela fornece arrays multidimensionais de alta performance e ferramentas para manipulação. O NumPy é essencial para tarefas como análise de dados, álgebra linear e otimização.
- **Matplotlib**: A biblioteca Matplotlib é uma biblioteca Python para criação de gráficos e visualização de dados. Ela oferece uma ampla gama de funções para criar gráficos 2D e 3D, incluindo histogramas, gráficos de dispersão, gráficos de linhas e muito mais. O Matplotlib é uma ferramenta poderosa para comunicar insights de dados de forma eficaz.

**Introdução**:

Neste repositório, serão implementadas diversas tarefas relacionadas à disciplina de Métodos Quantitativos utilizando as bibliotecas NumPy e Matplotlib. As tarefas abordarão conceitos como estatística descritiva, probabilidade, inferência estatística e regressão linear. Através da implementação prática, buscaremos solidificar o conhecimento teórico e desenvolver habilidades de programação para análise de dados.

Importação das bibliotecas

In [1]:
import numpy as np

O NumPy oferece diversas funções para a geração de arrays com valores aleatórios, permitindo a criação de conjuntos de dados para experimentos, simulações e análise estatística. Neste trabalho, será explorado as principais funções de inicialização randômica do NumPy e seus usos práticos.

**Exemplos:**

1. Array unidimensional com 10 números aleatórios entre 0 e 1:

In [2]:
random_array = np.random.rand(10)
random_array

array([0.89516201, 0.28993616, 0.06819741, 0.88904376, 0.7600917 ,
       0.51272267, 0.89090341, 0.43373272, 0.85260612, 0.52502091])

2. Gerando um array unidimensional com 5 números aleatórios distribuídos normalmente:

In [3]:
normal_randon_array = np.random.randn(5) 
normal_randon_array

array([ 0.88322215, -0.545298  , -0.44478278, -0.23386582, -0.89111361])

3. Gerando um array unidimensional com 15 números inteiros aleatórios maiores que 0 e menores que 20

In [8]:
randon_int_array = np.random.randint(low=0, high=20, size=15)
randon_int_array

array([ 0,  4,  9, 16,  4, 10, 14, 13, 14, 16, 14,  0,  0, 15, 19])

### Arrays Bidimensionais com NumPy
As mesmas funções de inicialização randômica do NumPy vistas anteriormente podem ser utilizadas para gerar arrays bidimensionais (matrizes). Basta especificar a forma do array como argumento, informando o número de linhas e colunas desejadas. Por exemplo, para gerar uma matriz 2x3 com números aleatórios entre 0 e 1:

In [10]:
randon_matrix = np.random.rand(2, 3)
randon_matrix

array([[0.37057637, 0.27566248, 0.03831312],
       [0.09404363, 0.03671729, 0.05599205]])

### Exemplos de Operações com Matrizes no NumPy

O NumPy fornece diversas funções para realizar operações matemáticas com matrizes, abrangendo desde operações básicas como adição e subtração até operações mais complexas como multiplicação de matrizes e inversão de matrizes.

A seguir serão demonstrados alguns exemplos práticos de operações com matrizes no NumPy.

1. Definição de duas matrizes aleatórias 3x3

In [13]:
random_matrix_1 = np.random.rand(3, 3)
random_matrix_1

array([[0.24497364, 0.61909257, 0.60488465],
       [0.97590593, 0.63856715, 0.92133642],
       [0.53581587, 0.92683181, 0.02806919]])

In [14]:
random_matrix_2 = np.random.rand(3, 3)
random_matrix_2

array([[0.81132167, 0.20544876, 0.92512654],
       [0.72138587, 0.14462953, 0.74461225],
       [0.08834721, 0.46654631, 0.68844828]])

2. Adição e Subtração de Matrizes

A adição e subtração de matrizes só podem ser realizadas se as matrizes tiverem as mesmas dimensões. A soma de dois elementos na mesma posição das matrizes resulta em um novo elemento na mesma posição da matriz resultante.

In [15]:
sum = random_matrix_1 + random_matrix_2
sum

array([[1.05629531, 0.82454133, 1.53001118],
       [1.69729179, 0.78319668, 1.66594866],
       [0.62416308, 1.39337813, 0.71651747]])

In [16]:
sub = random_matrix_1 - random_matrix_2
sub

array([[-0.56634803,  0.41364381, -0.32024189],
       [ 0.25452006,  0.49393762,  0.17672417],
       [ 0.44746866,  0.4602855 , -0.6603791 ]])